# Generated by Django 3.1 on 2020-08-08 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 31, 18, 60229, tzinfo=utc))),
                ('activity_period', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
