# Generated by Django 3.1 on 2020-08-08 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='tz',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 11, 31, 44, 21398, tzinfo=utc)),
        ),
    ]
