# Generated by Django 3.1 on 2020-08-08 11:35

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20200808_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='tz',
            field=timezone_field.fields.TimeZoneField(default='America/Los_Angeles'),
        ),
    ]
