# Generated by Django 3.1 on 2020-08-08 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20200808_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 18, 10, 38, 664755))),
                ('end_time', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 18, 10, 38, 664755))),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(choices=[('America/Los_Angeles', 'America/Los_Angeles'), ('Asia/Kolkata', 'Asia/Kolkata')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TimeZone',
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ManyToManyField(to='rest_api.Category'),
        ),
    ]
